# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 15:09
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xbus', '0004_auto_20161224_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envelope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('envelope_id', models.CharField(blank=True, max_length=80, null=True)),
                ('direction', models.CharField(choices=[(b'in', 'Incoming'), (b'out', 'Outgoing'), (b'immediate-out', 'Immediate-Out')], max_length=25)),
                ('state', models.CharField(choices=[(b'pending', 'Pending'), (b'done', 'Done'), (b'error', 'Error')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='event',
            name='state',
        ),
        migrations.AddField(
            model_name='event',
            name='envelope',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='xbus.Envelope'),
        ),
    ]
